version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  cars_api:
    build: .
    depends_on:
      - db
    ports:
      - 5000:80
  auth_api:
    build: ./user-auth
    ports:
      - 3000:3000
